# Generated by Django 2.1 on 2019-06-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0003_auto_20190613_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
